camel:
  batch:
    timeout: 100
    max:
      records: 100
  springboot:
    main-run-controller: true

noop:
  flag: true
inputPath: file:/Users/v4u2chat/Dev/data/inbox

dbRoute1: jdbc:dataSource
sqlInsertStmt: INSERT INTO `CampaignData` (`ID`,`SOURCE_ACCOUNT_NBR`, `PRODUCT_CODE`, `MAX_DISPLAY_COUNT`, `UPLOAD_DATE`, `DELETE_DATE`, `CAMPAIGN_TYPE`, `MESSAGE1`, `MESSAGE2`, `MESSAGE3`, `MESSAGE4`, `PRIORITY`, `ACTION`,`SOURCE_ACCOUNT_NBR_MD5`) VALUES (:#UUID,:#SOURCE_ACCOUNT_NBR, :#PRODUCT_CODE, :#MAX_DISPLAY_COUNT, STR_TO_DATE(:#UPLOAD_DATE,'%d-%m-%Y'),STR_TO_DATE(:#DELETE_DATE,'%d-%m-%Y'), :#CAMPAIGN_TYPE, :#MESSAGE1, :#MESSAGE2, :#MESSAGE3, :#MESSAGE4, :#PRIORITY, :#ACTION, MD5(:#SOURCE_ACCOUNT_NBR));

spring:
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ags-data-poc
    username: root
    password: mysql#123
    jdbc-url: jdbc:mysql://localhost:3306/ags-data-poc
  batch:
    initialize-schema: always