CREATE TABLE `CompaignData` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SOURCE_ACCOUNT_NBR` varchar(45) DEFAULT NULL,
  `PRODUCT_CODE` varchar(45) DEFAULT NULL,
  `MAX_DISPLAY_COUNT` varchar(45) DEFAULT NULL,
  `UPLOAD_DATE` date DEFAULT NULL,
  `DELETE_DATE` date DEFAULT NULL,
  `CAMPAIGN_TYPE` varchar(45) DEFAULT NULL,
  `MESSAGE1` longtext,
  `MESSAGE2` longtext,
  `MESSAGE3` longtext,
  `MESSAGE4` longtext,
  `PRIORITY` int DEFAULT NULL,
  `ACTION` varchar(45) DEFAULT NULL,
  `SOURCE_ACCOUNT_NBR_MD5` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
